import type {
  HumansOptions,
  LlmsOptions,
  RobotsOptions,
  SecurityOptions,
  SitemapOptions,
  SiteFilesOptions,
} from '@casoon/astro-site-files';

// The configuration this site passes to @casoon/astro-site-files in astro.config.mjs.
// The showcase prints each block below next to the file it produced in this build.

const home = 'https://casoon.github.io/astro-site-files/';

export const robots: RobotsOptions = {
  // Search engines and AI assistants may read and cite the docs; training crawlers may not.
  preset: 'citationFriendly',
};

export const llms: LlmsOptions = {
  title: 'astro-site-files',
  description:
    'Astro integration that generates robots.txt, llms.txt, sitemap.xml, security.txt and humans.txt at build time from typed configuration.',
  details:
    'Published on npm as @casoon/astro-site-files. Requires Node.js 22.12 or newer and Astro 6 or newer. MIT licensed.',
  sections: [
    {
      title: 'Documentation',
      links: [
        { title: 'Installation', url: `${home}docs/getting-started/installation/` },
        { title: 'Quickstart', url: `${home}docs/getting-started/quickstart/` },
        { title: 'robots.txt', url: `${home}docs/configuration/robots-txt/`, description: 'Presets, bot groups and path rules' },
        { title: 'llms.txt', url: `${home}docs/configuration/llms-txt/` },
        { title: 'sitemap.xml', url: `${home}docs/configuration/sitemap-xml/`, description: 'Discovery, priorities, i18n and sources' },
        { title: 'RSS feed', url: `${home}docs/configuration/rss/` },
        { title: 'security.txt', url: `${home}docs/configuration/security-txt/` },
        { title: 'humans.txt', url: `${home}docs/configuration/humans-txt/` },
        { title: 'API overview', url: `${home}docs/reference/api/` },
      ],
    },
    {
      title: 'Project',
      links: [
        { title: 'Source code', url: 'https://github.com/casoon/astro-site-files' },
        { title: 'npm package', url: 'https://www.npmjs.com/package/@casoon/astro-site-files' },
        { title: 'Changelog', url: `${home}changelog/` },
      ],
    },
  ],
};

// On by default. Every page Astro builds is listed, with the base path applied.
export const sitemap: SitemapOptions = {};

export const security: SecurityOptions = {
  contact: 'mailto:info@casoon.de',
  // RFC 9116 recommends less than a year; every build moves the date forward.
  expires: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
  preferredLanguages: ['en', 'de'],
  canonical: `${home}.well-known/security.txt`,
};

export const humans: HumansOptions = {
  team: [{ name: 'Jörn Seidel', role: 'Author and maintainer' }],
  technology: ['Astro', 'TypeScript', '@casoon/astro-site-files', '@casoon/pages-theme'],
  note: 'This file, robots.txt, llms.txt, sitemap.xml and security.txt are generated by @casoon/astro-site-files during the site build.',
};

export const siteFilesOptions: SiteFilesOptions = { robots, llms, sitemap, security, humans };
